// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaPlaceSalesAPI.Model.DBContext;

#nullable disable

namespace PizzaPlaceSalesAPI.Migrations
{
    [DbContext(typeof(PizzaDBContext))]
    [Migration("20240405154408_PizzaDbMigration")]
    partial class PizzaDbMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PizzaPlaceSalesAPI.Model.OrderDetailsModel", b =>
                {
                    b.Property<int>("order_details_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("order_details_id"));

                    b.Property<int>("pizza_idid")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("order_details_id");

                    b.HasIndex("pizza_idid");

                    b.ToTable("order_details");
                });

            modelBuilder.Entity("PizzaPlaceSalesAPI.Model.OrderModel", b =>
                {
                    b.Property<int>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("order_id"));

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("time")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("order_id");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("PizzaPlaceSalesAPI.Model.PizzaTypeModel", b =>
                {
                    b.Property<string>("pizza_type_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("pizza_type_id");

                    b.ToTable("pizza_type");
                });

            modelBuilder.Entity("PizzaPlaceSalesAPI.Model.PizzasModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("pizza_id")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("pizza_type_id1")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("size")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.HasKey("id");

                    b.HasIndex("pizza_type_id1");

                    b.ToTable("pizzas");
                });

            modelBuilder.Entity("PizzaPlaceSalesAPI.Model.OrderDetailsModel", b =>
                {
                    b.HasOne("PizzaPlaceSalesAPI.Model.PizzasModel", "pizza_id")
                        .WithMany()
                        .HasForeignKey("pizza_idid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pizza_id");
                });

            modelBuilder.Entity("PizzaPlaceSalesAPI.Model.PizzasModel", b =>
                {
                    b.HasOne("PizzaPlaceSalesAPI.Model.PizzaTypeModel", "pizza_type_id")
                        .WithMany()
                        .HasForeignKey("pizza_type_id1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pizza_type_id");
                });
#pragma warning restore 612, 618
        }
    }
}
